site_name: AI/ML Learning Notes
site_url: https://jjietay.github.io/AI_ML_Learning/

nav:
  - Home: index.md
  - Theory:
    - Neuron: theory/1_neuron.md
    - CNN: theory/2_cnn.md
    - SE Block: theory/3_se_block.md
    - Dropout & Coadaptation: theory/4_dropout_coadaptation.md
    - RNN: theory/5_rnn.md
    - Transformers & Attention: theory/6_transformers_attention.md
    - Multilayer Perceptrons: theory/7_multilayer_perceptrons.md
    - ReLU & Gated: theory/8_relu_gated.md
    - BERT: theory/bert.md
    - DiT: theory/dit.md
    - Ensemble: theory/ensemble.md
    - GAN: theory/gan.md
    - GRU: theory/gru.md
    - LSTM: theory/lstm.md
    - Swin Transformer: theory/swin_transformer.md
    - Vanishing Gradients: theory/vanishing_grad.md
    - ViT: theory/vit.md

theme:
  name: material

plugins:
  - search